# Generated by Django 5.0.2 on 2024-02-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image1',
            field=models.ImageField(null=True, upload_to='cars_images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(null=True, upload_to='cars_images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(null=True, upload_to='cars_images'),
        ),
    ]
