# Generated by Django 5.0.2 on 2024-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_car_image2_alter_car_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(null=True, upload_to='cars_images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(null=True, upload_to='cars_images'),
        ),
    ]
