# Generated by Django 5.0.2 on 2024-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_car_number_alter_car_image2_alter_car_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
